# Site settings
title: pwnaccelerator BLOG
email: 
description: > # this means to ignore newlines until "baseurl:"
  security and maybe more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pwnaccelerator.github.io" # the base hostname & protocol for your site
twitter_username: marver
github_username:  pwnaccelerator

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
